version: '3.8'
services:
  torrserver:
    image: ghcr.io/yourok/torrserver
    container_name: torrserver
    # network_mode: host # to allow DLNA feature
    environment:
      - TS_PORT=5665
      - TS_DONTKILL=1
      - TS_HTTPAUTH=0
      - TS_CONF_PATH=/opt/ts/config
      - TS_TORR_DIR=/opt/ts/torrents
    volumes:
      - './torrserver/cache:/opt/ts/torrents'
      - './torrserver/config:/opt/ts/config'
    ports:
      - '5665:5665'
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - ./jackett/data:/config
      - ./jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Europe/London
    ports:
      - "8191:8191"
    restart: unless-stopped

  lampa:
    image: node:18
    command: /bin/sh
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./lampa:/home/node/app
    working_dir: /home/node/app
    user: node
    environment:
      - NODE_ENV=production
    tty: true
    # restart: unless-stopped
